### PR TITLE
implement red header, add image on club page

### PR DESCRIPTION
**Pull request by ttonyan10**
just a start, prob didn't need to do a PR but the color and fonts feel good :)

### CODE REVIEW

**Comment by ttonyan10** [comment]
@charwking am I safe to merge?

**Comment by charwking** [comment]
I'm not sure it's valid HTML to have that `<wrapper>` tag outside the `<body>`, but we can clean that up on a future PR. Looks cool! Merge at your discretion.

**Comment by charwking** [comment]
Now live in DEV. :)

**Comment by ttonyan10** [comment]
wahoo!!!

**Pull request merged**
